name: Go

on:
  push:
  pull_request:
  workflow_dispatch:
  create:
  delete:

jobs:
  build-1:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 111111111
  build-2:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-3:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-4:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-5:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-6:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-7:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-8:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-9:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-10:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-11:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-12:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-13:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-14:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-15:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-16:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-17:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-18:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-19:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
  build-20:
    runs-on: tenki-local-ubuntu-22.04-small-2c-4g
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111111
