name: Go

on:
  push:
  pull_request:
  workflow_dispatch:
  create:
  delete:

jobs:
  build-1:
    runs-on: tenki-staging-standard-autoscale
    steps:
      - uses: actions/checkout@v4
      - name: Sleep and Print
        run: |
          sleep 20
          echo 11111
